name: CI/CD_Task

on:
  push:
    branches:
      - "main"
      
jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devopstask1:latest


  DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'stranger7771981/DevOps-Task1'
          ssh-known-host: ${{ secrets.HOST}}
      - run: ls -la
      - run: |
         sudo apt-get install -y ansible
         
      - run: ansible-playbook -i hosts.txt playbook_setup_app.yml
      
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_GITHUB_ACTION }}
          
 
      
          
  
