name: CI/CD_Task

on:
  push:
    branches:
      - "main"
      
jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devopstask1:latest


  DEPLOY:
    runs-on: ubuntu-latest
    
    steps:
      - name: ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: 192.46.236.15
          username: devops
          key: ${{ secrets.SSH_GITHUB_ACTION }}
          
      - name: git clone    
        uses: actions/checkout@v3
        with:
          repository: 'stranger7771981/DevOps-Task1' 
      - name: INSTALL ANSIBLE 
      
        run: sudo apt-get install -y ansible
      - name: PWD
        run: |
         ls -la 
         pwd 
      #- name: RUN PLAYBOOK
       # run: ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook -i hosts.yml --extra-vars "ansible_host=devops@192.168.31.164 ansible_password=lucky777 host_key_checking = False" playbook_setup_app.yml
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
    # Required, playbook filepath
          playbook: playbook_setup_app.yml
    # Optional, directory where playbooks live
          #directory: ./Devops-Task1
    # Optional, SSH private key
          key: ${{secrets.ANSIBLE_GITHUB_ACTION}}
    # Optional, literal inventory file contents
          inventory: hosts.yml
    # Optional, SSH known hosts file content
          #known_hosts: .known_hosts

         
      
      
          
 
      
          
  
