name: CI/CD_Task

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devopstask1:latest
          
  connection:
    runs-on: ubuntu-latest
    steps:
      - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          ORIGIN: ${{ secrets.UBUNTU_SERVER_LOGIN }}
          SSHKEY: ${{ secrets.SSH_GITHUB_ACTION }}
          USER: ${{ secrets.UBUNTU_SERVER_LOGIN }}
      - run: ansible-playbook -i hosts.yml playbook_setup_app.yml -K   
          
  
