name: CI/CD_Task

on:
  push:
    branches:
      - "main"
      
jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devopstask1:latest


  DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: 192.46.236.15
          username: devops
          key: ${{ secrets.SSH_GITHUB_ACTION }}
            
          
      - run: ls -la 
      - uses: actions/checkout@v3
        with:
          repository: 'stranger7771981/DevOps-Task1'
      - run: ls -la
      - run: |
         sudo apt-get install -y ansible
         
      - run: ansible-playbook -i hosts.yml playbook_setup_app.yml
          
 
      
          
  
